// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckkrogkfdstroqgudqgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNra3JvZ2tmZHN0cm9xZ3VkcWdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzcyMTIsImV4cCI6MjA2MjgxMzIxMn0.7NLpftlEnZ2QtEC4bvwtebTbd-0hr5Ey8uo29HfO1ac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);